"""
A conversational trip-planning assistant -- IMPORTANT: this is rule-based
keyword/intent parsing, not a large language model. No external AI API is
called. Be honest about this distinction in any documentation: it's a
legitimate, explainable technique (structured intent extraction + filtered
ranking), just not "real" natural language understanding. A message like
"I want cheap street food near Chinatown" is parsed by matching known
keywords against fixed vocabularies below, not by any model that
"understands" the sentence.

Swapping this for a real LLM later (OpenAI, Anthropic, etc.) would need an
API key and a paid account -- there's no free, no-signup equivalent to
what MyMemory/Nominatim are for translation/geocoding elsewhere in this
project, which is why this stays rule-based for now.
"""
import re

from django.db.models import Q

from .models import FoodExperience

# Keyword -> category. Checked as substrings against the lowercased message.
CATEGORY_KEYWORDS = {
    "street food": FoodExperience.Category.STREET_FOOD,
    "hawker": FoodExperience.Category.STREET_FOOD,
    "fine dining": FoodExperience.Category.FINE_DINING,
    "upscale": FoodExperience.Category.FINE_DINING,
    "fancy": FoodExperience.Category.FINE_DINING,
    "cooking class": FoodExperience.Category.COOKING_CLASS,
    "cook": FoodExperience.Category.COOKING_CLASS,
    "market": FoodExperience.Category.MARKET_TOUR,
    "tour": FoodExperience.Category.MARKET_TOUR,
    "tasting": FoodExperience.Category.TASTING,
    "taste": FoodExperience.Category.TASTING,
}

# Known areas from this project's seed data addresses. Matched as substrings
# against each experience's `address` field.
KNOWN_AREAS = [
    "chinatown", "katong", "little india", "ang mo kio", "geylang",
    "tiong bahru", "amoy street", "maxwell", "dunlop",
]

BUDGET_PATTERN = re.compile(r"(?:under|below|less than|budget of|\$)\s*\$?(\d+)", re.IGNORECASE)


def parse_intent(message):
    """Extract (categories, areas, max_budget) from a free-text message."""
    lowered = message.lower()

    categories = {cat for keyword, cat in CATEGORY_KEYWORDS.items() if keyword in lowered}
    areas = [area for area in KNOWN_AREAS if area in lowered]

    budget_match = BUDGET_PATTERN.search(lowered)
    max_budget = float(budget_match.group(1)) if budget_match else None

    return {
        "categories": list(categories),
        "areas": areas,
        "max_budget": max_budget,
    }


def plan_trip(message, base_queryset, max_stops=4):
    """
    Returns (reply_text, matched_experiences) -- a template-composed reply
    (not generated by any model) plus a ranked, capped list of experiences
    matching whatever was parsed from the message. base_queryset should
    already be scoped to what the requesting user is allowed to see.
    """
    intent = parse_intent(message)
    qs = base_queryset

    if intent["categories"]:
        qs = qs.filter(category__in=intent["categories"])
    if intent["areas"]:
        area_filter = Q()
        for area in intent["areas"]:
            area_filter |= Q(address__icontains=area)
        qs = qs.filter(area_filter)
    if intent["max_budget"] is not None:
        qs = qs.filter(price__lte=intent["max_budget"])

    matched = list(qs.order_by("-avg_rating", "-created_at")[: max_stops * 3])
    matched = _diversify_by_category(matched, max_stops)

    reply = _compose_reply(intent, matched)
    return reply, matched


def _diversify_by_category(experiences, max_stops):
    """Prefer variety: don't recommend 4 near-identical tasting sessions if
    the pool has other categories available, without a real diversity
    algorithm -- just a simple greedy pass."""
    seen_categories = set()
    diverse, leftovers = [], []
    for exp in experiences:
        if exp.category not in seen_categories:
            diverse.append(exp)
            seen_categories.add(exp.category)
        else:
            leftovers.append(exp)
        if len(diverse) == max_stops:
            return diverse
    return (diverse + leftovers)[:max_stops]


def _compose_reply(intent, matched):
    if not matched:
        return (
            "I couldn't find anything matching that -- try loosening the "
            "budget or mentioning a different area or type of food."
        )

    parts = ["Here's what I found"]
    if intent["categories"]:
        readable = ", ".join(c.replace("_", " ") for c in intent["categories"])
        parts.append(f"for {readable}")
    if intent["areas"]:
        parts.append(f"around {', '.join(intent['areas'])}")
    if intent["max_budget"] is not None:
        parts.append(f"under ${intent['max_budget']:.0f}")
    return " ".join(parts) + f": {len(matched)} stop{'s' if len(matched) != 1 else ''} for your trip."
