"""
A conversational trip-planning assistant -- IMPORTANT: this is rule-based
keyword/intent parsing, not a large language model. No external AI API is
called. Be honest about this distinction in any documentation: it's a
legitimate, explainable technique (structured intent extraction + filtered
ranking), just not "real" natural language understanding. A message like
"I want cheap street food near Chinatown" is parsed by matching known
keywords against fixed vocabularies below, not by any model that
"understands" the sentence.

Swapping this for a real LLM later (OpenAI, Anthropic, etc.) would need an
API key and a paid account -- there's no free, no-signup equivalent to
what MyMemory/Nominatim are for translation/geocoding elsewhere in this
project, which is why this stays rule-based for now.
"""
import re

from django.db.models import Q

from .models import FoodExperience

# Keyword -> category. Checked as substrings against the lowercased message.
CATEGORY_KEYWORDS = {
    "street food": FoodExperience.Category.STREET_FOOD,
    "hawker": FoodExperience.Category.STREET_FOOD,
    "fine dining": FoodExperience.Category.FINE_DINING,
    "upscale": FoodExperience.Category.FINE_DINING,
    "fancy": FoodExperience.Category.FINE_DINING,
    "cooking class": FoodExperience.Category.COOKING_CLASS,
    "cook": FoodExperience.Category.COOKING_CLASS,
    "market": FoodExperience.Category.MARKET_TOUR,
    "tour": FoodExperience.Category.MARKET_TOUR,
    "tasting": FoodExperience.Category.TASTING,
    "taste": FoodExperience.Category.TASTING,
}

# Known areas from this project's seed data addresses. Matched as substrings
# against each experience's `address` field. Kept in sync with
# seed_demo_data.py -- if you add a vendor in a new area, add it here too,
# or the trip planner will silently ignore that area in messages.
KNOWN_AREAS = [
    "chinatown", "katong", "little india", "ang mo kio", "geylang",
    "tiong bahru", "amoy street", "maxwell", "dunlop", "jalan pisang",
    "kampong glam", "dempsey", "armenian", "joo chiat", "new bridge",
    "east coast",
]

BUDGET_PATTERN = re.compile(r"(?:under|below|less than|budget of|\$)\s*\$?(\d+)", re.IGNORECASE)

# How many stops the person actually asked for -- e.g. "just one restaurant",
# "recommend 2 places", "a single spot". Previously this was never parsed at
# all, so a request for exactly one place still got up to 4 back (the
# hardcoded default), spread across different categories by
# _diversify_by_category -- which is why the results looked "inaccurate".
WORD_TO_NUMBER = {
    "one": 1, "a": 1, "an": 1, "single": 1, "just one": 1,
    "two": 2, "couple": 2, "a couple": 2, "a couple of": 2,
    "three": 3, "few": 3, "a few": 3,
    "four": 4,
}
COUNT_DIGIT_PATTERN = re.compile(
    r"\b(\d+)\s*(?:restaurant|place|stop|spot|experience|option|recommendation)s?\b",
    re.IGNORECASE,
)
COUNT_WORD_PATTERN = re.compile(
    r"\b(one|a single|just one|a couple of|a couple|couple|two|a few|few|three|four)\s*"
    r"(?:restaurant|place|stop|spot|experience|option|recommendation)s?\b",
    re.IGNORECASE,
)


def parse_intent(message):
    """Extract (categories, areas, max_budget, requested_count) from free text."""
    lowered = message.lower()

    categories = {cat for keyword, cat in CATEGORY_KEYWORDS.items() if keyword in lowered}
    areas = [area for area in KNOWN_AREAS if area in lowered]

    budget_match = BUDGET_PATTERN.search(lowered)
    max_budget = float(budget_match.group(1)) if budget_match else None

    requested_count = None
    digit_match = COUNT_DIGIT_PATTERN.search(lowered)
    if digit_match:
        requested_count = int(digit_match.group(1))
    else:
        word_match = COUNT_WORD_PATTERN.search(lowered)
        if word_match:
            requested_count = WORD_TO_NUMBER.get(word_match.group(1).strip())

    return {
        "categories": list(categories),
        "areas": areas,
        "max_budget": max_budget,
        "requested_count": requested_count,
    }


def plan_trip(message, base_queryset, max_stops=4):
    """
    Returns (reply_text, matched_experiences) -- a template-composed reply
    (not generated by any model) plus a ranked, capped list of experiences
    matching whatever was parsed from the message. base_queryset should
    already be scoped to what the requesting user is allowed to see.

    If the message names a specific number of places (e.g. "just one
    restaurant"), that overrides max_stops and skips the category-diversity
    pass below -- diversifying across categories only makes sense when
    several stops were actually asked for.
    """
    intent = parse_intent(message)
    qs = base_queryset

    if intent["categories"]:
        qs = qs.filter(category__in=intent["categories"])
    if intent["areas"]:
        area_filter = Q()
        for area in intent["areas"]:
            area_filter |= Q(address__icontains=area)
        qs = qs.filter(area_filter)
    if intent["max_budget"] is not None:
        qs = qs.filter(price__lte=intent["max_budget"])

    stops_wanted = intent["requested_count"] or max_stops
    matched = list(qs.order_by("-avg_rating", "-created_at")[: stops_wanted * 3])

    if intent["requested_count"]:
        # An explicit count means "give me exactly this many, best match
        # first" -- not "spread these across different categories".
        matched = matched[:stops_wanted]
    else:
        matched = _diversify_by_category(matched, stops_wanted)

    reply = _compose_reply(intent, matched)
    return reply, matched


def _diversify_by_category(experiences, max_stops):
    """Prefer variety: don't recommend 4 near-identical tasting sessions if
    the pool has other categories available, without a real diversity
    algorithm -- just a simple greedy pass."""
    seen_categories = set()
    diverse, leftovers = [], []
    for exp in experiences:
        if exp.category not in seen_categories:
            diverse.append(exp)
            seen_categories.add(exp.category)
        else:
            leftovers.append(exp)
        if len(diverse) == max_stops:
            return diverse
    return (diverse + leftovers)[:max_stops]


def _compose_reply(intent, matched):
    if not matched:
        return (
            "I couldn't find anything matching that -- try loosening the "
            "budget or mentioning a different area or type of food."
        )

    if intent["requested_count"] and len(matched) < intent["requested_count"]:
        parts = [f"I could only find {len(matched)} matching that (you asked for {intent['requested_count']})"]
    else:
        parts = ["Here's what I found"]
    if intent["categories"]:
        readable = ", ".join(c.replace("_", " ") for c in intent["categories"])
        parts.append(f"for {readable}")
    if intent["areas"]:
        parts.append(f"around {', '.join(intent['areas'])}")
    if intent["max_budget"] is not None:
        parts.append(f"under ${intent['max_budget']:.0f}")
    return " ".join(parts) + f": {len(matched)} stop{'s' if len(matched) != 1 else ''} for your trip."
