# Generated by Django 5.2.9 on 2026-09-03 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_entries', to='core.foodexperience')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_stops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['planned_date', 'order', 'added_at'],
                'unique_together': {('tourist', 'experience')},
            },
        ),
        migrations.CreateModel(
            name='SavedExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.foodexperience')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('tourist', 'experience')},
            },
        ),
    ]
