# Generated by Django 5.2.9 on 2026-09-07 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itinerarystop_savedexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodExperienceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('zh', 'Chinese (Simplified)'), ('ms', 'Bahasa Melayu')], max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.foodexperience')),
            ],
            options={
                'unique_together': {('experience', 'language')},
            },
        ),
    ]
