# Generated by Django 5.2.9 on 2026-09-11 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foodexperiencetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='hours_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VendorTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('zh', 'Chinese (Simplified)'), ('ms', 'Bahasa Melayu')], max_length=5)),
                ('business_name', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.vendor')),
            ],
            options={
                'unique_together': {('vendor', 'language')},
            },
        ),
    ]
